### PR TITLE
using Beacon for in app support

### PR DESCRIPTION
**Pull request by jlopker**

### CODE REVIEW

**Review by chime-mu — COMMENTED** [review]
@jlopker I've tested the beacon functionality and it seems to work from the UI POV. I've reported two issues , but don't know where they're received? (maybe I'm just being impatient and they arrive later).
Do I need to do something specific to make it run on my own machine?
Do we have a Beacon account where we see stats or set things up? If yes, could you document a bit about that somewhere? Maybe in a MD file in the doc directory.

**Comment by jlopker** [comment]
@chime-mu i just turned on all your email notifications so you should get an email anytime someone sends a message thru Beacon

I invited you to HelpScout, the company that makes Beacon. Did you see an invite come thru?

**Comment by chime-mu** [comment]
@jlopker Unfortunately I've been too slow so the HelpScout invitation expired. Can you send me another one?

**Comment by chime-mu** [comment]
Another point we haven't spend a lot of time on previously, but it seems some people are actually installing cobudget from source. So we need some way to disable the Beacon integration and some way to configure the account. 
And actually we need to test the system still works without Beacon.

**Comment by jlopker** [comment]
@chime-mu i just sent you another invite. something to think about - we have to pay per user for HelpScout ($8/month/user). I was just able to extend my trial till Jan 19th but i'm not sure we necessarily need both of us as users at least for a bit. i'm anticipating not getting many support requests for a while. what do you think?

i'm not sure familiar with that kind of configuration.. do you have an idea of what that would look like? will figuring that up hold up the deploy of this feature?

**Comment by chime-mu** [comment]
@jlopker Thnak for the invite. I've signed up.

I agree we only need one user as long as traffic is low, so if you're fine with handling support, we should remove me again.

**Comment by chime-mu** [comment]
@jlopker As per the conversation we had the other day, we should add a simple way to configure the account to use when we use beacon and then not check our own account in, but keep that in a separate environment specific configuration.

We should also test that if there's no beacon account configured, the beacon functionality is disabled.

When we talked about you sounded like you had a clear about how you would do it. If you're still not sure about the best way, let me know and I'll be happy to come up with a suggestion.

**Comment by jlopker** [comment]
@chime-mu i just pushed a change that's not about hiding the env variable but instead just uses an angular if statement to check if the user is on our site. let me know if you think this is a good solution!

**Comment by chime-mu** [comment]
@jlopker No, I'm not really happy about that solution for several reasons:

* We still have private info about our HelpScout account directly checked in to the code.
* It's too easy to lift your restriction and then get support from us - and we would never ever notice this happening.

Besides, don't we have the same problem with GA tracking codes?

I think it's long overdue that we can get config info to the frontend, for all kind of product integrated to the frontend. It's also a solution that we could use for other almost constant information such as the currency table etc.

**Pull request merged**
