### PR TITLE
New funded bucket table on activity tab with CSV downloads

### PR DESCRIPTION
**Pull request by jlopker**

### CODE REVIEW

**Comment by chime-mu** [comment]
@jlopker email is not included in the on-screen list, but is part of the CSV and "Created at" is on screen but not in the CSV. Maybe this is by design, but it's slightly confusing.

**Comment by chime-mu** [comment]
@jlopker When downloading CSV using firefox there's no file type suffix (.csv or similar), so Excel or Numbers will no open by default.

**Comment by chime-mu** [comment]
@jlopker The list in the activity tab looks very similar and with the same info as the **Funded** list in the Buckets tab - does it really make sense to replicate it in the activity tab?

**Comment by jlopker** [comment]
@chime-mu 
Thanks for the feedback re points 1+2 (pushed those changes) 
I agree about the similarities with the info.. Maybe we don't actually need this table and rather just the csv download button on the header of the Funded buckets list. I'll talk with Fran about it.

**Comment by jlopker** [comment]
@chime-mu I talked with Fran, and we determined that we want this table here (even tho it might seem repetitive) because we want there to be one place where the admin can go to get all the necessary information. Can you review again? Thanks!

**Pull request merged**
